stages:
  - unit_tests
  - integration_tests

unit_test:
  image: node:12.6.0-slim
  stage: unit_tests
  script:
  - yarn
  - yarn test

vpnpeer_integration_test:
  image: web3f/secure-validator-ci:v0.2.0
  stage: integration_tests
  services:
  - docker:18.09-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
  script:
  - cd ansible/roles/vpnpeer
  - molecule test

polkadot_validator_integration_test:
  image: web3f/secure-validator-ci:v0.2.0
  stage: integration_tests
  services:
  - docker:18.09-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
  script:
  - cd ansible/roles/polkadot-validator
  - molecule test

polkadot_public_integration_test:
  image: web3f/secure-validator-ci:v0.2.0
  stage: integration_tests
  services:
  - docker:18.09-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
  script:
  - cd ansible/roles/polkadot-public
  - molecule test

common_integration_test:
  image: web3f/secure-validator-ci:v0.2.0
  stage: integration_tests
  services:
  - docker:18.09-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
  script:
  - cd ansible/roles/common
  - molecule test
