stages:
  - unit_tests
  - integration_tests
  - deployment

unit_test:
  image: node:12.6.0-slim
  stage: unit_tests
  script:
  - yarn
  - yarn test
  only:
  - pushes

common_integration_test:
  image: web3f/secure-validator-ci:v0.2.0
  stage: integration_tests
  services:
  - docker:18.09-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
  script:
  - cd ansible/roles/common
  - molecule test
  only:
  - pushes

polkadot_common_integration_test:
  image: web3f/secure-validator-ci:v0.2.0
  stage: integration_tests
  services:
  - docker:18.09-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
  script:
  - cd ansible/roles/polkadot-common
  - molecule test
  only:
  - pushes

polkadot_public_integration_test:
  image: web3f/secure-validator-ci:v0.2.0
  stage: integration_tests
  services:
  - docker:18.09-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
  script:
  - cd ansible/roles/polkadot-public
  - molecule test
  only:
  - pushes

polkadot_validator_integration_test:
  image: web3f/secure-validator-ci:v0.2.0
  stage: integration_tests
  services:
  - docker:18.09-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
  script:
  - cd ansible/roles/polkadot-validator
  - molecule test
  only:
  - pushes

vpnpeer_integration_test:
  image: web3f/secure-validator-ci:v0.2.0
  stage: integration_tests
  services:
  - docker:18.09-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
  script:
  - cd ansible/roles/vpnpeer
  - molecule test
  only:
  - pushes

vpnpeer_setup_integration_test:
  image: web3f/secure-validator-ci:v0.2.0
  stage: integration_tests
  services:
  - docker:18.09-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
  script:
  - cd ansible/roles/vpnpeer-setup
  - molecule test
  only:
  - pushes

deploy:
  image: web3f/secure-validator-ci:v0.2.0
  stage: deployment
  script:
  - scripts/deploy.sh
  only:
  - /v[0-9]+(\.[0-9]+)*/
