stages:
  - validate

unit_test:
  image: node:12.6.0-slim
  stage: validate
  script:
  - yarn
  - yarn test

integration_test:
  image: web3f/secure-validator-ci:v0.1.0
  stage: validate
  services:
  - docker:18.09-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
  script:
  - cd ansible/roles/secure-validator
  - molecule --debug create
  - molecule converge
