---
# tasks file for polkadot-validator
- name: firewall setup
  import_tasks: firewall.yml

- name: journald config
  import_tasks: journald.yml

- name: user and group
  import_tasks: user.yml

- name: proxy setup
  import_tasks: proxy.yml

- name: service setup
  import_tasks: service.yml

- name: install binary
  import_role:
    name: polkadot-update-binary

- name: session management
  import_tasks: session.yml
