---
# tasks file for common
- name: install ufw
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: ufw already enabled
  command: ufw status verbose
  register: ufw_status_result
  changed_when: False

- name: open ssh port
  command: ufw allow ssh
  when: not ufw_status_result.stdout is search("22/tcp.*ALLOW IN.*Anywhere")

- name: open vpn port
  command: ufw allow {{ vpn_port }}/udp
  when: not ufw_status_result.stdout is search(vpn_port ~ "/udp.*ALLOW IN.*Anywhere")

- name: open p2p port
  command: ufw allow {{ p2p_port }}/tcp
  when: not ufw_status_result.stdout is search(p2p_port ~ "/tcp.*ALLOW IN.*Anywhere")

- name: enable firewall
  shell: echo "y" | ufw enable
  when: not ufw_status_result.stdout is search("Status.* active")
