version: 2

jobs:
  lint:
    docker:
      - image: node:10.15-alpine
    steps:
      - checkout
      - run: yarn
      - run:
          name: Run tests
          command: |
            yarn test

  integrationTest:
    docker:
      - image: web3f/secure-validator-ci:v1.0.0
    steps:
      - checkout
      - run:
          name: Copy credentials
          command: echo $GOOGLE_APPLICATION_CREDENTIALS_CONTENT > $(pwd)/credentials.json
      - run:
          name: test content
            command: cat $(pwd)/credentials.json
      - run:
          name: Set credentials path
          command: export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/credentials.json
      - run:
          name: test creds
            command: echo $GOOGLE_APPLICATION_CREDENTIALS
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: integrationTest
          command: ./scripts/integrationTest.sh

  publishPackage:
    docker:
      - image: node:10.15-alpine
    steps:
      - checkout
      - run:
          name: Publish package
          command: npm publish --userconfig=.npmrc-auth

workflows:
  version: 2
  test-deploy:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - integrationTest:
          filters:
            tags:
              only: /.*/
          requires:
            - lint
      - publishPackage:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
