ansibleIntegrationTest: &ansibleIntegrationTest
    docker:
      - image: web3f/secure-validator-ci:v1.1.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: execute molecule tests for the ansible role at $ROLE_PATH
          command: |
            cd $ROLE_PATH
            molecule test

version: 2

jobs:
  unitTests:
    docker:
      - image: web3f/node:v0.1.0
    steps:
      - checkout
      - run: yarn
      - run:
          name: Run tests
          command: |
            yarn test

  commonIntegrationTest:
    environment:
      ROLE_PATH: ansible/roles/common
    <<: *ansibleIntegrationTest

  polkadotCommonIntegrationTest:
    environment:
      ROLE_PATH: ansible/roles/polkadot-common
    <<: *ansibleIntegrationTest

  polkadotPublicIntegrationTest:
    environment:
      ROLE_PATH: ansible/roles/polkadot-public
    <<: *ansibleIntegrationTest

  polkadotValidatorIntegrationTest:
    environment:
      ROLE_PATH: ansible/roles/polkadot-validator
    <<: *ansibleIntegrationTest

  vpnpeerIntegrationTest:
    environment:
      ROLE_PATH: ansible/roles/vpnpeer
    <<: *ansibleIntegrationTest

  vpnpeerSetupIntegrationTest:
    environment:
      ROLE_PATH: ansible/roles/vpnpeer-setup
    <<: *ansibleIntegrationTest

  polkadotValidatorSessionInfoIntegrationTest:
    environment:
      ROLE_PATH: ansible/roles/polkadot-validator-session-info
    <<: *ansibleIntegrationTest

  nodeExporterIntegrationTest:
    environment:
      ROLE_PATH: ansible/roles/node-exporter
    <<: *ansibleIntegrationTest

  integrationTest:
    docker:
      - image: web3f/secure-validator-ci:v1.1.1
    steps:
      - checkout
      - run:
          name: Copy credentials
          command: echo $GOOGLE_APPLICATION_CREDENTIALS_CONTENT > $(pwd)/credentials.json
      - run:
          name: Yarn install
          command: yarn
      - run:
          name: integrationTest
          command: ./scripts/integrationTest.sh

  publishPackage:
    docker:
      - image: web3f/node:v0.1.0
    steps:
      - checkout
      - run:
          name: Publish package
          command: npm publish --userconfig=.npmrc-auth

workflows:
  version: 2
  test-deploy:
    jobs:
      - unitTests:
          filters:
            tags:
              only: /.*/
      - commonIntegrationTest:
          filters:
            tags:
              only: /.*/
          requires:
            - unitTests
      - polkadotCommonIntegrationTest:
          filters:
            tags:
              only: /.*/
          requires:
            - unitTests
      - polkadotPublicIntegrationTest:
          filters:
            tags:
              only: /.*/
          requires:
            - unitTests
      - polkadotValidatorIntegrationTest:
          filters:
            tags:
              only: /.*/
          requires:
            - unitTests
      - polkadotValidatorSessionInfoIntegrationTest:
          filters:
            tags:
              only: /.*/
          requires:
            - unitTests
      - vpnpeerIntegrationTest:
          filters:
            tags:
              only: /.*/
          requires:
            - unitTests
      - vpnpeerSetupIntegrationTest:
          filters:
            tags:
              only: /.*/
          requires:
            - unitTests
      - nodeExporterIntegrationTest:
          filters:
            tags:
              only: /.*/
          requires:
            - unitTests
      - integrationTest:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - commonIntegrationTest
            - polkadotCommonIntegrationTest
            - polkadotPublicIntegrationTest
            - polkadotValidatorIntegrationTest
            - polkadotValidatorSessionInfoIntegrationTest
            - vpnpeerIntegrationTest
            - vpnpeerSetupIntegrationTest
            - nodeExporterIntegrationTest
      - publishPackage:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - integrationTest
