---
# tasks file for polkadot
- name: create polkadot group
  group:
    name: polkadot
    state: present

- name: add polkadot user
  user:
    name: polkadot
    group: polkadot
    append: yes

- name: polkadot binary checksum
  shell: |
    set -o pipefail
    if [ -f /usr/local/bin/polkadot ] && \
       [ -f  /etc/systemd/system/polkadot.service ] && \
       [ "$(echo -n '{{ polkadot_binary_checksum }}' | cut -f1 -d':')" != "$(cat /usr/local/bin/polkadot | sha256sum | cut -f1 -d' ')" ]; then
      echo yes
    else
      echo no
    fi
  args:
    executable: /bin/bash
  register: should_upgrade
  changed_when: False

- name: download polkadot binary
  get_url:
    url: '{{ polkadot_binary_url | quote }}'
    checksum: '{{ polkadot_binary_checksum | quote }}'
    dest: /usr/local/bin/polkadot-new
    mode: '0700'
    owner: 'polkadot'
    group: 'polkadot'

- name: check if polkadot service is running
  shell: |
    set -o pipefail
    systemctl is-active --quiet polkadot
    if [ "$?" == 0 ]; then
      echo yes
    else
      cp /usr/local/bin/polkadot-new /usr/local/bin/polkadot
      chown polkadot:polkadot /usr/local/bin/polkadot
      echo no
    fi
  args:
    executable: /bin/bash
  register: polkadot_service_running
  changed_when: false

- name: create polkadot dummy config
  template:
    src: polkadot.service.j2
    dest: /etc/systemd/system/polkadot.service
    owner: root
    group: root
    mode: 0600
  when: polkadot_service_running.stdout == "no"

- name: start polkadot dummy service
  systemd:
    name: polkadot.service
    state: started
  changed_when: false
  when: polkadot_service_running.stdout == "no"

- name: save networkState
  uri:
    url: http://localhost:9933
    method: "POST"
    body_format: json
    body: |
      { "jsonrpc":"2.0", "method":"system_networkState", "params":[], "id":1 }
  register: network_state
  until: network_state.status == 200
  retries: 5
  delay: 5

- name: set peer id as fact
  set_fact:
    p2p_peer_id: "{{ network_state.json.result.peerId }}"

- name: stop polkadot dummy service
  systemd:
    name: polkadot.service
    state: stopped
  changed_when: false
  when: polkadot_service_running.stdout == "no"

- name: cronjob for restarting polkadot service
  cron:
    name: "restart polkadot"
    minute: "{{ polkadot_restart_minute }}"
    hour: "{{ polkadot_restart_hour }}"
    day: "{{ polkadot_restart_day }}"
    month: "{{ polkadot_restart_month }}"
    weekday: "{{ polkadot_restart_weekday }}"
    job: "/bin/systemctl restart polkadot.service"
  when: "polkadot_restart_enabled|default(false)|bool"
