---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: polkadot-validator-validator-node
    image: ubuntu:bionic
    groups:
      - validator
  - name: polkadot-validator-public-node
    image: ubuntu:bionic
    groups:
      - public
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:

    host_vars:
      polkadot-validator-validator-node:
        vpnpeer_address: 10.0.0.1
        polkadot_network_id: ksma
      polkadot-validator-public-node:
        vpnpeer_address: 10.0.0.2
        p2p_peer_id: peerid
        polkadot_network_id: ksma
verifier:
  name: testinfra
  lint:
    name: flake8
