---
# tasks file for polkadot-public
- name: create polkadot service file
  template:
    src: polkadot.service.j2
    dest: /etc/systemd/system/polkadot.service
    owner: root
    group: root
    mode: 0600

- name: start polkadot service
  systemd:
    name: polkadot.service
    state: started
    enabled: yes

- name: save networkState
  uri:
    url: http://localhost:9933
    method: "POST"
    body_format: json
    body: |
      { "jsonrpc":"2.0", "method":"system_networkState", "params":[], "id":1 }
  register: network_state

- name: set peer id as fact
  set_fact:
    p2p_peer_id: "{{ network_state.json.result.peerId }}"
