subkey_binary_url: 'https://github.com/w3f/substrate/releases/download/e0f3fa/subkey'
subkey_binary_checksum: 'sha256:f74a06442e76c3bb97d27a168b9710ef062ae5640ad82e7d42b8fb613f8be9d9'
polkadot_network_id: 'ksmcc2'
build_dir: '/tmp'
