---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: validator
    image: ubuntu:bionic
    volumes:
      - /dev/net/tun:/dev/net/tun
    capabilities:
      - NET_ADMIN
    groups:
      - validator
  - name: public
    image: ubuntu:bionic
    volumes:
      - /dev/net/tun:/dev/net/tun
    capabilities:
      - NET_ADMIN
    groups:
      - public
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      validator:
        vpnpeer_address: 10.0.0.1
        vpn_private_key: vpn_secret1
        vpnpeer_cidr_suffix: 24
        vpn_public_key: vpn_public1
      public:
        vpnpeer_address: 10.0.0.2
        vpn_private_key: vpn_secret2
        vpnpeer_cidr_suffix: 24
        vpn_public_key: vpn_public2
verifier:
  name: testinfra
  lint:
    name: flake8
